export const initialState = {
  USER: [
    {
      ID: 101, // ID
      EMAIL: 'hyundai123@naver.com', // 이메일
      INTRODUCE: '안녕 반가워요', // 한 줄 소개
      PROFILE: 'localhost:5173/src',
    },
    {
      ID: 101, // ID
      EMAIL: 'hyundai999@naver.com', // 이메일
      INTRODUCE: 'ㅎㅇㅎㅇㅎㅇ', // 한 줄 소개
      PROFILE: 'localhost:5173/src',
    },
    {
      ID: 103, // ID
      EMAIL: 'hyndaicar97@gmail.com',
      INTRODUCE: '한줄 소개 입니다',
      PROFILE: 'localhost:5173/src',
    },
    {
      ID: 104,
      EMAIL: 'hyundai99@daum.net',
      INTRODUCE: 'ㅎㅇㅎㅇㅎㅇ',
      PROFILE: 'localhost:5173/src',
    },
    {
      ID: 105,
      EMAIL: 'devops@kakao.com',
      INTRODUCE: '남자 입니다',
      PROFILE: 'localhost:5173/src',
    },
    {
      ID: 106,
      EMAIL: 'frontback@naver.com',
      INTRODUCE: '안녕하세요',
      PROFILE: 'localhost:5173/src',
    },
    {
      ID: 107,
      EMAIL: 'hyundaiAuto@naver.com',
      INTRODUCE: '잘 부탁드립니다.',
      PROFILE: 'localhost:5173/src',
    },
    {
      ID: 108,
      EMAIL: '42dot@naver.com',
      INTRODUCE: '처음뵙겠습니다.',
      PROFILE: 'localhost:5173/src',
    },
    {
      ID: 109,
      EMAIL: 'kia979@naver.com',
      INTRODUCE: '안녕!',
      PROFILE: 'localhost:5173/src',
    },
  ],
  cards: [
    {
      id: 1,
      hostId: 101,
      title: '점심 같이 드실분 점심 같이 드실분',
      curr: 1,
      total: 4,
      isClosed: false,
      meetingDay: '1212-01-23T12:40:50',
      regionId: 5,
      categoryId: 18,
      // COMMENTLIST: [100001, 100002, 100003, 100004, 100005, 100006],
    },
    {
      id: 3,
      hostId: 101,
      title: '강남구 축구부원 모집합니다.',
      curr: 1,
      total: 99,
      isClosed: false,
      meetingDay: '1212-01-23T12:40:50',
      regionId: 1,
      categoryId: 1,
    },
    {
      id: 4,
      hostId: 101,
      title: '대전 유성국 독서모임',
      curr: 3,
      total: 4,
      isClosed: false,
      meetingDay: '1212-02-23T12:40:50',
      regionId: 9,
      categoryId: 6,
    },
    {
      id: 6,
      hostId: 101,
      title: '모각코',
      curr: 9,
      total: 49,
      isClosed: false,
      meetingDay: '1212-01-23T12:40:50',
      regionId: 10,
      categoryId: 4,
    },
    {
      id: 9,
      hostId: 101,
      title: '미술관 같이 갈 예쁜 여성분 구해요',
      curr: 1,
      total: 2,
      isClosed: false,
      meetingDay: '1212-01-23T12:40:50',
      regionId: 10,
      categoryId: 6,
    },
    {
      id: 10,
      hostId: 101,
      title: '아침 운동 할사람',
      curr: 1,
      total: 2,
      isClosed: false,
      meetingDay: '1212-11-30T12:40:50',
      regionId: 17,
      categoryId: 2,
    },
    {
      id: 11,
      hostId: 103,
      title: '예수님의 사랑을 느껴보아요.-온누리교회',
      curr: 1,
      total: 2,
      isClosed: false,
      meetingDay: '1212-11-30T12:40:50',
      regionId: 1,
      categoryId: 11,
    },
  ],
  COMMENT: [
    {
      ID: 100001,
      ARTICLEID: 1,
      USERID: 101,
      DATE: new Date(),
      CONTENT: '바람도 서롤 감싸게 했죠',
    },
    {
      ID: 100002,
      ARTICLEID: 1,
      USERID: 103,
      DATE: new Date(),
      CONTENT: '햇살은 우릴 위해 내리고',
    },
    {
      ID: 100003,
      ARTICLEID: 1,
      USERID: 101,
      DATE: new Date(),
      CONTENT: '우리 웃음속에 계절은 오고 또 갔죠',
    },
    {
      ID: 100004,
      ARTICLEID: 1,
      USERID: 103,
      DATE: new Date(),
      CONTENT: '바람에 흔들리는 머릿결',
    },
    {
      ID: 100005,
      ARTICLEID: 1,
      USERID: 105,
      DATE: new Date(),
      CONTENT: '내게 불어오는 그대 향기',
    },
    {
      ID: 100006,
      ARTICLEID: 1,
      USERID: 103,
      DATE: new Date(),
      CONTENT: '예쁜 두눈도 웃음 소리도',
    },
    {
      ID: 100007,
      ARTICLEID: 2,
      USERID: 105,
      DATE: new Date(),
      CONTENT: '모두 다 내 것이었죠',
    },
    {
      ID: 100008,
      ARTICLEID: 2,
      USERID: 103,
      DATE: new Date(),
      CONTENT: '이런 사랑 이런 행복 쉽다 했었죠',
    },
    {
      ID: 100009,
      ARTICLEID: 2,
      USERID: 105,
      DATE: new Date(),
      CONTENT: '이런 웃음 이런 축복 내게 쉽게 올리 없죠',
    },
    {
      ID: 100010,
      ARTICLEID: 2,
      USERID: 103,
      DATE: new Date(),
      CONTENT: '눈물 조차 울음조차 닦지 못한 나',
    },
  ],
};
